### ISSUE TITLE
caseSensitive option no longer defaults to false, contrary to the readme

### ISSUE THREAD

**Issue by DSom20** [mthadley/eslint-plugin-sort-destructure-keys#73]
The current readme file on line 54, under the caseSensitive title/section, reads:
```
When `true` the rule will enforce properties to be in case-sensitive order. Default is `false`.
```

However, using version 1.3.5, I am getting the opposite behavior. The default value seems to be `true`. It looks like originally when the caseSensitive option was first introduced in [this commit](https://github.com/mthadley/eslint-plugin-sort-destructure-keys/commit/8f718eaa2eb4a44ddf91d862a876dab69b67dcf1#diff-8bbf6ae09a163b9782b439239d980cd9), the default was `false`, according to line 73 of `lib/rules/sort-destructure-keys.js`:
```javascript
const caseSensitive = options.caseSensitive || false;
```
However, the [next commit](https://github.com/mthadley/eslint-plugin-sort-destructure-keys/commit/c234e23c5850087740d7c9c3ba03321859df4386#diff-8bbf6ae09a163b9782b439239d980cd9) associated with that file deletes that line as part of a refactor, using new logic on line 110 to make the default `true`:
```javascript
const {caseSensitive = true} = options;
```
That logic is still in the current version of the file, on line 169.

Suggestion: Either change the readme to say the default is `true`, or change the code logic to actually default to `false`.

**Comment by mthadley** [comment]
Thanks for catching that, and doing such thorough code sleuthing.

Since the "real" default has been `false` for over a year now, I'd probably update the readme instead of publishing a new version with default flipped (unless someone firmly believes that the default should be `false`).

If you'd like to fix it yourself, PRs are welcome. Otherwise, I'll get to it in a bit.
